language: go
go:
- "1.11"

jobs:
  include:
  - stage: build
    before_script:
    - export BINDIR=${GOPATH}/bin
    - curl -L https://git.io/vp6lP | sh
    script:
    - make check

  - stage: build
    script:
    - make test
    after_success:
    - ${GOPATH}/bin/goveralls -coverprofile=./coverage.out -service=travis-ci
    after_script:
    - make clean
