language: go
go:
- "1.11"

before_script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- make test

after_success:
- ${GOPATH}/bin/goveralls -coverprofile=coverage.out -service=travis-ci
